# Company to Brand_SKU_Item mapping from Sagar's list
# Structure: { "Brand_SKU_Item": "Company Name" }

SAGAR_MAPPING = {
    "[COLOR] ANY GARNIER OVERALL [ANY CR ME]": "L'OREAL INDIA",
    "[HCEXL] GARNIER BLACK NATURALS": "L'OREAL INDIA",
    "[HCEXL] GARNIER COLOUR NATRALS": "L'OREAL INDIA",
    "[HCEXL] LOREAL": "L'OREAL INDIA",
    "[HCEXL] GARNIER MEN SHAMPOO COLOUR SHAMPOO": "L'OREAL INDIA",
    "[HCEXL] MATRIX SOCOLOR PREBONDED CREAM HAIR COLO": "L'OREAL INDIA",
    "[HCEXL] NISHA POWDER [ANY HERBAL BASED PWD]": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] NISHA CREME": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] NISHA POWDER": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] NISHA HENNA [ANY HERBAL BASED PWD]": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] PREM KAVERI [ANY HERBAL BASED PWD]": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HEXLI] NISHA POWDER": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] NISHA SHAMPOO HAIR COLOR": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "[HCEXL] GODREJ EXPERT RICH CREME": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT ORIGINAL PWD(BLUE)": "GODREJ CONSUMER PRODS",
    "[HEXLI] GODREJ NUPUR MEHENDI": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXP EASY 5 MIN COLOR SHAMPOO": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ KALI MAHENDEI": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ SELFIE HAIR COLOUR SHAMPOO": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT CARE PWD(GREEN) [ANY HERBAL BASED PWD]": "GODREJ CONSUMER PRODS",
    "[HCEXL] NUPUR HBP [ANY HERBAL BASED PWD]": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT ADVANCED PWD(PINK)": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ NUPUR CREME": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ KESH KALA HAIR OIL": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ RENEW POWDER HAIR COLOUR": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ PERMENANT POW.HAIR DYE": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT NEW PWD(BLUEPACK)": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT POWDER HAIR COLO": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPE RICH CR ME FASHION RANGE": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ EXPERT POWDER HAIR DYE": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ RENEW HAIR COLOUR CREAM": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ PROESSIONAL COLOURPLAY CREAM HAIR": "GODREJ CONSUMER PRODS",
    "[HCEXL] GODREJ FASHION COLOUR": "GODREJ CONSUMER PRODS",
    "[HCEXL] SUPER VASMOL33 KESH KALA": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] STREAX HAIR COLOUR": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] SUPER VASMOL33 KALI MEHANDI": "HYGIENIC RESEARCH INSTITUTE",
    "[COLOR] ANY STREAX CREME [ANY CR ME]": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] SUPER VASMOL AMLA DYE": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] VASMOL AYURPRASH SHAMPOO HAIR": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] VASMOL": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] SUPER VASMOL AMLA HERBAL BROWN [ANY HERBAL BASED PWD]": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] SUPER VASMOL 33 BROWN AYURPRASH": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] VASMOL [ANY HERBAL BASED PWD]": "HYGIENIC RESEARCH INSTITUTE",
    "[HCEXL] INDICA": "CAVINKARE",
    "[COLOR] ANY INDICA CREME [ANY CR ME]": "CAVINKARE",
    "[HCEXL] CHIK HAIR COLOUR SHAMPOO": "CAVINKARE",
    "[HCEXL] CHIK KALI MEHANDI": "CAVINKARE",
    "[HCEXL] INDICA [ANY HERBAL BASED PWD]": "CAVINKARE",
    "[HCEXL] SPINZ NOURISHING HAIR COLOR CR": "CAVINKARE",
    "[HCEXL] CHIK QUICK CREME": "CAVINKARE",
    "[HCEXL] NEHA HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] UNBRANDED CLR'ANT/HENNA": "S C COMPANY",
    "[HEXLI] ADORE HENNA": "S C COMPANY",
    "[HEXLI] AMINA HENNA": "S C COMPANY",
    "[HEXLI] SHANKAR SUGANDHI HENNA": "S C COMPANY",
    "[HEXLI] BHAWNAGAR HENNA": "S C COMPANY",
    "[HCEXL] AFRIN HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] RAJASTHANI HENNA": "S C COMPANY",
    "[HCEXL] AYU  HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] BRITE HENNA": "S C COMPANY",
    "[HEXLI] AYUR HENNA POWDER": "S C COMPANY",
    "[HCEXL] ADORE HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] VLCC HENNA": "S C COMPANY",
    "[HEXLI] NOORJAHAN HENNA": "S C COMPANY",
    "[HEXLI] AYUR RAJAS NAT HENNA PWD": "S C COMPANY",
    "[HEXLI] AVON HENNA POWDER": "S C COMPANY",
    "[HEXLI] SHINGAR HENNA POWDER": "S C COMPANY",
    "[HCEXL] AMINA HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] SHELLY HENNA": "S C COMPANY",
    "[HCEXL] BRITE HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] NYLE HENNA": "S C COMPANY",
    "[HEXLI] BLACK NIGHT HENNA": "S C COMPANY",
    "[HEXLI] PAKEEJA HENNA": "S C COMPANY",
    "[HEXLI] MINAR HENNA POWDER": "S C COMPANY",
    "[HCEXL] VLCC HENNA [ANY HERBAL BASED PWD]": "S C COMPANY",
    "[HEXLI] L.D.H HENNA POWDER": "S C COMPANY",
    "[HEXLI] OTH.BRDED CLR'ANT/HENNA": "Others / Unmapped",
    "[HCEXL] OTH.BRDED CLR'ANT/HENNA [ANY HERBAL BASED PWD]": "Others / Unmapped",
    "[HCEXL] OTH.BRDED CLR'ANT/HENNA": "Others / Unmapped",
    "[COLOR] ANY OTHER BRANDED CREME [ANY CR ME]": "Others / Unmapped",
    "[HCEXL] BLACK ROSE KALI MEHANDI": "HEENA EXPORT CORPORATION",
    "[HCEXL] BLACK ROSE SHAMPOO": "HEENA EXPORT CORPORATION",
    "[HCEXL] BLACK ROSE HAIR COLOR": "HEENA EXPORT CORPORATION",
    "[HCEXL] BLACK ROSE POWDER DYE": "HEENA EXPORT CORPORATION",
    "[HEXLI] BLACK ROSE HERBAL HENNA P": "HEENA EXPORT CORPORATION",
    "[HCEXL] BLACK ROSE HENNA POWDER": "HEENA EXPORT CORPORATION",
    "[HCEXL] PREM DULHAN [ANY HERBAL BASED PWD]": "PREM GREEN PVT LTD",
    "[HEXLI] NEERA": "PREM GREEN PVT LTD",
    "[HEXLI] PREM DULHAN": "PREM GREEN PVT LTD",
    "[HCEXL] ZEBA [ANY HERBAL BASED PWD]": "EXCELL IMPEX",
    "[HEXLI] NIKHAR HENNA": "EXCELL IMPEX",
    "[HEXLI] EXCEL": "EXCELL IMPEX",
    "[HCEXL] EXCEL": "EXCELL IMPEX",
    "[HEXLI] POOJA NIKHAR HENNA": "EXCELL IMPEX",
    "[HCEXL] NIKHAR HENNA [ANY HERBAL BASED PWD]": "EXCELL IMPEX",
    "[HCEXL] BANJARA HENNA [ANY HERBAL BASED PWD]": "VISHAL INDS",
    "[HEXLI] BANJARA HENNA": "VISHAL INDS",
    "[HCEXL] VIP HAIR COLOUR SHAMPOO": "BUY HAPPY MARKETING LLP",
    "[HCEXL] COLORMATE [ANY HERBAL BASED PWD]": "HENNA INDUSTRIES PVT LTD",
    "[COLOR] ANY COLORMATE CREME [ANY CR ME]": "HENNA INDUSTRIES PVT LTD",
    "[HCEXL] PUSHP HENNA POWDER [ANY HERBAL BASED PWD]": "PUSHP ENTERPRISE",
    "[HCEXL] PUSHP HENNA [ANY HERBAL BASED PWD]": "PUSHP ENTERPRISE",
    "[HCEXL] VCARE COLORING SHAMPOO": "VCARE HERBAL CONCEPTS LTD",
    "[HCEXL] NEHA POWDER COLOUR [ANY HERBAL BASED PWD]": "NEHA ENTERPRISE",
    "[HCEXL] NEHA CREME": "NEHA ENTERPRISE",
    "[HCEXL] NEHA KALI MEHANDI": "NEHA ENTERPRISE",
    "[HCEXL] NEHA SHAMPOO HAIR COLOR": "NEHA ENTERPRISE",
    "[HCEXL] PATANJALI": "PATANJALI",
    "[HCEXL] PATANJALI [ANY HERBAL BASED PWD]": "PATANJALI",
    "[HEXLI] PATANJALI": "PATANJALI",
    "[HCEXL] MOON STAR [ANY HERBAL BASED PWD]": "IZUK CHEM",
    "[HCEXL] STERLING HENNA [ANY HERBAL BASED PWD]": "STERLING INTERNATIONAL",
    "[HEXLI] HERBAL HENNA POWDER": "HIMALAYAN MOUNTAIN PRODUCTS",
    "[HEXLI] SHENAI HERBAL HENNA": "HIMALAYAN MOUNTAIN PRODUCTS",
    "[HCEXL] HERBAL CHANDI DYE POWDER": "HIMALAYAN MOUNTAIN PRODUCTS",
    "[HCEXL] KAISH KALA HERBAL OIL": "HIMALAYAN MOUNTAIN PRODUCTS",
    "[HCEXL] BLACK DIAMOND HERBAL [ANY HERBAL BASED PWD]": "BABURAM OMPRAKASH",
    "[HCEXL] BLACK DIAMOND KAL.MEHENDI": "BABURAM OMPRAKASH",
    "[HCEXL] DIAMOND HENNA HAIR COLOR [ANY HERBAL BASED PWD]": "BABURAM OMPRAKASH",
    "[HEXLI] BLACK DIAMOND HENNA": "BABURAM OMPRAKASH",
    "[HCEXL] BLACK DIAMOND DYE": "BABURAM OMPRAKASH",
    "[HEXLI] DIAMOND HENNA HAIR COLOR": "BABURAM OMPRAKASH",
    "[HCEXL] MAYURI HENNA [ANY HERBAL BASED PWD]": "MAYURI HERBAL CARE PVT LTD",
    "[HEXLI] RANGOLI HENNA": "NEW RATHORE MEHANDI CENTER",
    "[HCEXL] PANCHVATI KALI MEHANDI": "BALDEV INDUSTRIES",
    "[HEXLI] PANCHVATI HENNA POWDER": "BALDEV INDUSTRIES",
    "[HCEXL] PANCHVATI HERBAL COLOUR CREAM": "BALDEV INDUSTRIES",
    "[HCEXL] SISO": "SISO COSMETICS PVT LTD",
    "[HCEXL] MAHURI HENNA [ANY HERBAL BASED PWD]": "SAWAN INDUSTRIES",
    "[HEXLI] GANPATI CHHAP MEHANDI": "JAIN INDUSTRIES",
    "[HEXLI] COLORINA HENNA": "EXIM INDIA COSMETICS COMPANY",
    "[HCEXL] 5 STAR": "FIVE STAR HEALTH CARE P. LTD",
    "[HCEXL] BIGEN B INSTANT COLOUR": "J L MORISON",
    "[HEXLI] DOUBLE HATTI MEHANDI": "DOUBLE HATHI HEENA PVT LTD",
    "[HEXLI] MILAN HENNA": "PARMANAND COMPANY",
    "[HCEXL] MODICARE SALON PROFESSIONAL": "MODICARE LIMITED",
    "[HCEXL] KAJAL HAIR HENNA [ANY HERBAL BASED PWD]": "KAJAL DULHAN MEHANDI CENTER",
    "[HEXLI] BLACK GOLD HENNA": "ABHINAN EXPORT",
    "[HCEXL] BBLUNT": "HONASA CONSUMER P LTD",
    "[HEXLI] PARAMPARA": "PARAMPARA",
    "[HCEXL] ORIFLAME": "ORIFLAME INDIA",
    "[HCEXL] ABIHA POWDER [ANY HERBAL BASED PWD]": "FRIENDS COSMETICS",
    "[HEXLI] DULHAN HENNA POWDER": "AMILAL RAM KISHAN DASS",
    "[HEXLI] SAHIBA HENNA": "BABU RAM DHARAM PRAKASH",
    "[HEXLI] RAWALDAS HENNA": "BHARAT RAWALDAS",
    "[HEXLI] HERBY HENNA PLUS": "HERBY INT.PVT LTD",
    "[HCEXL] CHANDAN HERBAL POWDER [ANY HERBAL BASED PWD]": "DEEWAL GROMODYOG",
    "[HEXLI] KANTA HENNA PLUS": "KANTA HERBALS",
    "[HCEXL] MSG [ANY HERBAL BASED PWD]": "IMPRESSION COSMETICS",
    "[HEXLI] ANOO'S HEENA": "ANOO'S ELECTOLYSIS OBESITY LTD",
    "[HEXLI] JOVEES": "JOVEES HERBAL CARE",
    "[HCEXL] JOVEES": "JOVEES HERBAL CARE",
    "[HCEXL] KHADIGRAM POWDER [ANY HERBAL BASED PWD]": "Review Required",
    "[HEXLI] RADHIKA": "Review Required",
    "[HCEXL] BLACK NITE KALI MEHANDI": "Review Required",
    "[HCEXL] AMWAY": "Review Required",
    "[HCEXL] HAIR4REAL": "Review Required",
    "[HCEXL] SILKIENCE": "Review Required",
    "[HCEXL] COLOR STAY HAIRCOLOR": "Review Required",
    "[HCEXL] CLEO": "Review Required",
    "[HCEXL] GRAM UDYOG POWDER [ANY HERBAL BASED PWD]": "Review Required",
    "[HCEXL] FARISHTA": "Review Required",
    "[HCEXL] GODREJ PROF.DIMENSION CREAM HAIR COLOR": "Review Required",
    "[HEXLI] JANNU MEHANDI": "SUPREME MEHANDI",
    "[HEXLI] VASMOL SHEHNAI": "DAULAT MEHANDI BHANDAR",
    "[HEXLI] ASHOK HINA": "ASHOK HINA",
    "[HCEXL] LIVON": "MARICO INDS",
    "[HEXLI] EVEREST HENNA": "K C J & CO",
    "[HCEXL] KORRA COLORING SHAMPOO": "RATAN ORGANICA INTERNATIONAL",
    "[HCEXL] PALETTE": "HENKEL",
    "[HCEXL] WELLA": "UNIVERSAL CORPORATION",
}

# Company keyword list for fuzzy matching
# Order matters: more specific keywords should come first
COMPANY_KEYWORDS = {
    "GARNIER": "L'OREAL INDIA",
    "LOREAL": "L'OREAL INDIA",
    "MATRIX SOCOLOR": "L'OREAL INDIA",
    "NISHA": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "PREM KAVERI": "PREM HENNA PVT LTD (YUTIKA NATURALS)",
    "GODREJ": "GODREJ CONSUMER PRODS",
    "NUPUR": "GODREJ CONSUMER PRODS",
    "VASMOL": "HYGIENIC RESEARCH INSTITUTE",
    "STREAX": "HYGIENIC RESEARCH INSTITUTE",
    "INDICA": "CAVINKARE",
    "CHIK": "CAVINKARE",
    "SPINZ": "CAVINKARE",
    "BLACK ROSE": "HEENA EXPORT CORPORATION",
    "PREM DULHAN": "PREM GREEN PVT LTD",
    "NEERA": "PREM GREEN PVT LTD",
    "NIKHAR": "EXCELL IMPEX",
    "EXCEL": "EXCELL IMPEX",
    "BANJARA": "VISHAL INDS",
    "VIP HAIR COLOUR": "BUY HAPPY MARKETING LLP",
    "COLORMATE": "HENNA INDUSTRIES PVT LTD",
    "PUSHP": "PUSHP ENTERPRISE",
    "VCARE": "VCARE HERBAL CONCEPTS LTD",
    "NEHA": "NEHA ENTERPRISE",
    "PATANJALI": "PATANJALI",
    "MOON STAR": "IZUK CHEM",
    "STERLING HENNA": "STERLING INTERNATIONAL",
    "KAISH KALA": "HIMALAYAN MOUNTAIN PRODUCTS",
    "BLACK DIAMOND": "BABURAM OMPRAKASH",
    "DIAMOND HENNA": "BABURAM OMPRAKASH",
    "MAYURI": "MAYURI HERBAL CARE PVT LTD",
    "RANGOLI": "NEW RATHORE MEHANDI CENTER",
    "PANCHVATI": "BALDEV INDUSTRIES",
    "SISO": "SISO COSMETICS PVT LTD",
    "MAHURI": "SAWAN INDUSTRIES",
    "BIGEN": "J L MORISON",
    "MODICARE": "MODICARE LIMITED",
    "KAJAL HAIR": "KAJAL DULHAN MEHANDI CENTER",
    "BBLUNT": "HONASA CONSUMER P LTD",
    "ORIFLAME": "ORIFLAME INDIA",
    "LIVON": "MARICO INDS",
    "KORRA": "RATAN ORGANICA INTERNATIONAL",
    "PALETTE": "HENKEL",
    "WELLA": "UNIVERSAL CORPORATION",
    "JOVEES": "JOVEES HERBAL CARE",
    "KANTA HENNA": "KANTA HERBALS",
    "HERBY": "HERBY INT.PVT LTD",
}

def get_company_name(sku_item: str, extra_mapping: dict = None, extra_keywords: dict = None) -> str:
    """
    Map a Brand_SKU_Item to its company name.
    Priority:
    1. User-provided extra mapping (uploaded list, fuzzy)
    2. User-provided extra keywords
    3. Sagar's exact list
    4. Built-in keyword matching
    5. "Others / Unmapped"
    """
    if not sku_item:
        return "Others / Unmapped"

    sku_upper = sku_item.upper().strip()

    # 1. User extra mapping (fuzzy - check if sku contains any mapped item as substring)
    if extra_mapping:
        for mapped_item, company in extra_mapping.items():
            if mapped_item.upper() in sku_upper or sku_upper in mapped_item.upper():
                return company

    # 2. User extra keywords
    if extra_keywords:
        for keyword, company in sorted(extra_keywords.items(), key=lambda x: -len(x[0])):
            if keyword.upper() in sku_upper:
                return company

    # 3. Exact match from Sagar's list
    if sku_item in SAGAR_MAPPING:
        return SAGAR_MAPPING[sku_item]

    # 4. Built-in keyword matching (longest keyword first for specificity)
    for keyword, company in sorted(COMPANY_KEYWORDS.items(), key=lambda x: -len(x[0])):
        if keyword.upper() in sku_upper:
            return company

    # 5. Fallback
    return "Others / Unmapped"

def get_all_company_names() -> list:
    """Return sorted list of all unique company names for autocomplete."""
    companies = set(SAGAR_MAPPING.values()) | set(COMPANY_KEYWORDS.values())
    return sorted(list(companies))
